version: '3'
  
services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  app:
    image: bitestoque:1.0
    depends_on:
      - postgres
    build: .
    ports:
      - '9292:9292'
    volumes:
      - .:/bitestoque
      - gems:/gems
    environment:
      - LANG=C.UTF-8

volumes:
  postgres:
  gems:
